// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.25.3
// source: f-taxes.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	FTaxes_SubmitTrade_FullMethodName      = "/FTaxesGrpc.FTaxes/SubmitTrade"
	FTaxes_SubmitTransfer_FullMethodName   = "/FTaxesGrpc.FTaxes/SubmitTransfer"
	FTaxes_SubmitGenericFee_FullMethodName = "/FTaxesGrpc.FTaxes/SubmitGenericFee"
	FTaxes_ShowJobProgress_FullMethodName  = "/FTaxesGrpc.FTaxes/ShowJobProgress"
	FTaxes_GetSettings_FullMethodName      = "/FTaxesGrpc.FTaxes/GetSettings"
	FTaxes_AppLog_FullMethodName           = "/FTaxesGrpc.FTaxes/AppLog"
	FTaxes_StreamRecords_FullMethodName    = "/FTaxesGrpc.FTaxes/StreamRecords"
	FTaxes_PluginHeartbeat_FullMethodName  = "/FTaxesGrpc.FTaxes/PluginHeartbeat"
)

// FTaxesClient is the client API for FTaxes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FTaxesClient interface {
	SubmitTrade(ctx context.Context, in *Trade, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SubmitTransfer(ctx context.Context, in *Transfer, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SubmitGenericFee(ctx context.Context, in *SrcGenericFee, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ShowJobProgress(ctx context.Context, in *JobProgress, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetSettings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Settings, error)
	AppLog(ctx context.Context, in *AppLogMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StreamRecords(ctx context.Context, in *StreamRecordsJob, opts ...grpc.CallOption) (FTaxes_StreamRecordsClient, error)
	PluginHeartbeat(ctx context.Context, in *PluginInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type fTaxesClient struct {
	cc grpc.ClientConnInterface
}

func NewFTaxesClient(cc grpc.ClientConnInterface) FTaxesClient {
	return &fTaxesClient{cc}
}

func (c *fTaxesClient) SubmitTrade(ctx context.Context, in *Trade, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FTaxes_SubmitTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fTaxesClient) SubmitTransfer(ctx context.Context, in *Transfer, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FTaxes_SubmitTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fTaxesClient) SubmitGenericFee(ctx context.Context, in *SrcGenericFee, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FTaxes_SubmitGenericFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fTaxesClient) ShowJobProgress(ctx context.Context, in *JobProgress, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FTaxes_ShowJobProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fTaxesClient) GetSettings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Settings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Settings)
	err := c.cc.Invoke(ctx, FTaxes_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fTaxesClient) AppLog(ctx context.Context, in *AppLogMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FTaxes_AppLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fTaxesClient) StreamRecords(ctx context.Context, in *StreamRecordsJob, opts ...grpc.CallOption) (FTaxes_StreamRecordsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FTaxes_ServiceDesc.Streams[0], FTaxes_StreamRecords_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &fTaxesStreamRecordsClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FTaxes_StreamRecordsClient interface {
	Recv() (*Record, error)
	grpc.ClientStream
}

type fTaxesStreamRecordsClient struct {
	grpc.ClientStream
}

func (x *fTaxesStreamRecordsClient) Recv() (*Record, error) {
	m := new(Record)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fTaxesClient) PluginHeartbeat(ctx context.Context, in *PluginInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FTaxes_PluginHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FTaxesServer is the server API for FTaxes service.
// All implementations must embed UnimplementedFTaxesServer
// for forward compatibility
type FTaxesServer interface {
	SubmitTrade(context.Context, *Trade) (*emptypb.Empty, error)
	SubmitTransfer(context.Context, *Transfer) (*emptypb.Empty, error)
	SubmitGenericFee(context.Context, *SrcGenericFee) (*emptypb.Empty, error)
	ShowJobProgress(context.Context, *JobProgress) (*emptypb.Empty, error)
	GetSettings(context.Context, *emptypb.Empty) (*Settings, error)
	AppLog(context.Context, *AppLogMsg) (*emptypb.Empty, error)
	StreamRecords(*StreamRecordsJob, FTaxes_StreamRecordsServer) error
	PluginHeartbeat(context.Context, *PluginInfo) (*emptypb.Empty, error)
	mustEmbedUnimplementedFTaxesServer()
}

// UnimplementedFTaxesServer must be embedded to have forward compatible implementations.
type UnimplementedFTaxesServer struct {
}

func (UnimplementedFTaxesServer) SubmitTrade(context.Context, *Trade) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTrade not implemented")
}
func (UnimplementedFTaxesServer) SubmitTransfer(context.Context, *Transfer) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTransfer not implemented")
}
func (UnimplementedFTaxesServer) SubmitGenericFee(context.Context, *SrcGenericFee) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitGenericFee not implemented")
}
func (UnimplementedFTaxesServer) ShowJobProgress(context.Context, *JobProgress) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowJobProgress not implemented")
}
func (UnimplementedFTaxesServer) GetSettings(context.Context, *emptypb.Empty) (*Settings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedFTaxesServer) AppLog(context.Context, *AppLogMsg) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppLog not implemented")
}
func (UnimplementedFTaxesServer) StreamRecords(*StreamRecordsJob, FTaxes_StreamRecordsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamRecords not implemented")
}
func (UnimplementedFTaxesServer) PluginHeartbeat(context.Context, *PluginInfo) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginHeartbeat not implemented")
}
func (UnimplementedFTaxesServer) mustEmbedUnimplementedFTaxesServer() {}

// UnsafeFTaxesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FTaxesServer will
// result in compilation errors.
type UnsafeFTaxesServer interface {
	mustEmbedUnimplementedFTaxesServer()
}

func RegisterFTaxesServer(s grpc.ServiceRegistrar, srv FTaxesServer) {
	s.RegisterService(&FTaxes_ServiceDesc, srv)
}

func _FTaxes_SubmitTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Trade)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FTaxesServer).SubmitTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FTaxes_SubmitTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FTaxesServer).SubmitTrade(ctx, req.(*Trade))
	}
	return interceptor(ctx, in, info, handler)
}

func _FTaxes_SubmitTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transfer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FTaxesServer).SubmitTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FTaxes_SubmitTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FTaxesServer).SubmitTransfer(ctx, req.(*Transfer))
	}
	return interceptor(ctx, in, info, handler)
}

func _FTaxes_SubmitGenericFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SrcGenericFee)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FTaxesServer).SubmitGenericFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FTaxes_SubmitGenericFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FTaxesServer).SubmitGenericFee(ctx, req.(*SrcGenericFee))
	}
	return interceptor(ctx, in, info, handler)
}

func _FTaxes_ShowJobProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobProgress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FTaxesServer).ShowJobProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FTaxes_ShowJobProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FTaxesServer).ShowJobProgress(ctx, req.(*JobProgress))
	}
	return interceptor(ctx, in, info, handler)
}

func _FTaxes_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FTaxesServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FTaxes_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FTaxesServer).GetSettings(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FTaxes_AppLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppLogMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FTaxesServer).AppLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FTaxes_AppLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FTaxesServer).AppLog(ctx, req.(*AppLogMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _FTaxes_StreamRecords_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRecordsJob)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FTaxesServer).StreamRecords(m, &fTaxesStreamRecordsServer{ServerStream: stream})
}

type FTaxes_StreamRecordsServer interface {
	Send(*Record) error
	grpc.ServerStream
}

type fTaxesStreamRecordsServer struct {
	grpc.ServerStream
}

func (x *fTaxesStreamRecordsServer) Send(m *Record) error {
	return x.ServerStream.SendMsg(m)
}

func _FTaxes_PluginHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FTaxesServer).PluginHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FTaxes_PluginHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FTaxesServer).PluginHeartbeat(ctx, req.(*PluginInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// FTaxes_ServiceDesc is the grpc.ServiceDesc for FTaxes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FTaxes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FTaxesGrpc.FTaxes",
	HandlerType: (*FTaxesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTrade",
			Handler:    _FTaxes_SubmitTrade_Handler,
		},
		{
			MethodName: "SubmitTransfer",
			Handler:    _FTaxes_SubmitTransfer_Handler,
		},
		{
			MethodName: "SubmitGenericFee",
			Handler:    _FTaxes_SubmitGenericFee_Handler,
		},
		{
			MethodName: "ShowJobProgress",
			Handler:    _FTaxes_ShowJobProgress_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _FTaxes_GetSettings_Handler,
		},
		{
			MethodName: "AppLog",
			Handler:    _FTaxes_AppLog_Handler,
		},
		{
			MethodName: "PluginHeartbeat",
			Handler:    _FTaxes_PluginHeartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRecords",
			Handler:       _FTaxes_StreamRecords_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "f-taxes.proto",
}

const (
	PluginCtl_ConvertPricesInTrade_FullMethodName    = "/FTaxesGrpc.PluginCtl/ConvertPricesInTrade"
	PluginCtl_ConvertPricesInTransfer_FullMethodName = "/FTaxesGrpc.PluginCtl/ConvertPricesInTransfer"
)

// PluginCtlClient is the client API for PluginCtl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginCtlClient interface {
	ConvertPricesInTrade(ctx context.Context, in *TradeConversionJob, opts ...grpc.CallOption) (*Trade, error)
	ConvertPricesInTransfer(ctx context.Context, in *TransferConversionJob, opts ...grpc.CallOption) (*Transfer, error)
}

type pluginCtlClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginCtlClient(cc grpc.ClientConnInterface) PluginCtlClient {
	return &pluginCtlClient{cc}
}

func (c *pluginCtlClient) ConvertPricesInTrade(ctx context.Context, in *TradeConversionJob, opts ...grpc.CallOption) (*Trade, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Trade)
	err := c.cc.Invoke(ctx, PluginCtl_ConvertPricesInTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginCtlClient) ConvertPricesInTransfer(ctx context.Context, in *TransferConversionJob, opts ...grpc.CallOption) (*Transfer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transfer)
	err := c.cc.Invoke(ctx, PluginCtl_ConvertPricesInTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginCtlServer is the server API for PluginCtl service.
// All implementations must embed UnimplementedPluginCtlServer
// for forward compatibility
type PluginCtlServer interface {
	ConvertPricesInTrade(context.Context, *TradeConversionJob) (*Trade, error)
	ConvertPricesInTransfer(context.Context, *TransferConversionJob) (*Transfer, error)
	mustEmbedUnimplementedPluginCtlServer()
}

// UnimplementedPluginCtlServer must be embedded to have forward compatible implementations.
type UnimplementedPluginCtlServer struct {
}

func (UnimplementedPluginCtlServer) ConvertPricesInTrade(context.Context, *TradeConversionJob) (*Trade, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertPricesInTrade not implemented")
}
func (UnimplementedPluginCtlServer) ConvertPricesInTransfer(context.Context, *TransferConversionJob) (*Transfer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertPricesInTransfer not implemented")
}
func (UnimplementedPluginCtlServer) mustEmbedUnimplementedPluginCtlServer() {}

// UnsafePluginCtlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginCtlServer will
// result in compilation errors.
type UnsafePluginCtlServer interface {
	mustEmbedUnimplementedPluginCtlServer()
}

func RegisterPluginCtlServer(s grpc.ServiceRegistrar, srv PluginCtlServer) {
	s.RegisterService(&PluginCtl_ServiceDesc, srv)
}

func _PluginCtl_ConvertPricesInTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeConversionJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginCtlServer).ConvertPricesInTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginCtl_ConvertPricesInTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginCtlServer).ConvertPricesInTrade(ctx, req.(*TradeConversionJob))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginCtl_ConvertPricesInTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferConversionJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginCtlServer).ConvertPricesInTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginCtl_ConvertPricesInTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginCtlServer).ConvertPricesInTransfer(ctx, req.(*TransferConversionJob))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginCtl_ServiceDesc is the grpc.ServiceDesc for PluginCtl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginCtl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FTaxesGrpc.PluginCtl",
	HandlerType: (*PluginCtlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertPricesInTrade",
			Handler:    _PluginCtl_ConvertPricesInTrade_Handler,
		},
		{
			MethodName: "ConvertPricesInTransfer",
			Handler:    _PluginCtl_ConvertPricesInTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "f-taxes.proto",
}
